config:
  # 集群地址列表
  serverA: eureka-server-9001
  serverB: eureka-server-9002
  serverC: eureka-server-9003

  # 集群端口列表
  portA: 9001
  portB: 9002
  portC: 9003

spring:
  application:
    name: gateway-server #服务名称
  cloud:
    gateway:
      default-filters:
      routes:
        - id:  user-server
          # lb代表从注册中心获取服务
          uri: lb://user
          predicates:
            # 转发该路径
            - Path=/user/**
          # 带前缀
          filters:
            - StripPrefix=1
        - id:  publish-server
          uri: lb://publish
          predicates:
            - Path=/publish/**
          filters:
            - StripPrefix=1
server:
  port: 9008 #服务端口

# Eureka配置
eureka:
  instance:
    # 是否微服务调用地址为IP优先(缺省值false)
    prefer-ip-address: false

    # 主机名称
    #hostname: ${config.serverA}

    # 设置机器IP
    ip-address: 127.0.0.1

    # 设置注册中心微服务名(默认为：机器主机名:应用名称:应用端口)
    #instance-id: ${eureka.instance.hostname}:${server.port}
    instance-id: ${eureka.instance.ip-address}:${server.port}

    # 客户端向服务器发送心跳的频率(缺省值30s)
    lease-renewal-interval-in-seconds: 30

  client:
    # 是否将自己作为客户端注册到注册中心(缺省值true)
    register-with-eureka: true

    # 是否从注册中心获取注册信息(缺省值true)
    fetch-registry: true

    # 从注册中心获取注册信息的间隔时间(缺省值30s)
    # 测试环境，可以适当提高Client端拉取Server注册信息的频率
    registry-fetch-interval-seconds: 30

    service-url:
      defaultZone: "http://${config.serverA}:${config.portA}/eureka/, \
                    http://${config.serverB}:${config.portB}/eureka/, \
                    http://${config.serverC}:${config.portC}/eureka/"